# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
TOPMODEL Configuration.

Pydantic schema and configuration adapter for TOPMODEL settings.
"""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from symfluence.models.base.base_config import AutoGeneratedConfigAdapter


class TOPMODELConfig(BaseModel):
    """
    TOPMODEL configuration schema.

    Defines all configurable aspects of TOPMODEL including runtime options,
    calibration settings, and initial state values.
    """

    # =========================================================================
    # Runtime Configuration
    # =========================================================================
    backend: Literal['jax', 'numpy'] = Field(
        default='jax',
        description="Computation backend. 'jax' for autodiff/JIT, 'numpy' for fallback."
    )

    warmup_days: int = Field(
        default=365,
        ge=0,
        description="Number of warmup days for model spinup."
    )

    # =========================================================================
    # Calibration Configuration
    # =========================================================================
    params_to_calibrate: str = Field(
        default='default',
        description=(
            "Comma-separated list of parameters to calibrate. "
            "'default' or empty string triggers use of all available parameters."
        )
    )

    calibration_metric: Literal['KGE', 'NSE'] = Field(
        default='KGE',
        description="Objective function for calibration."
    )

    # =========================================================================
    # PET Configuration
    # =========================================================================
    pet_method: Literal['input', 'oudin', 'hamon'] = Field(
        default='input',
        description="PET calculation method. 'input' uses provided PET, others compute from temperature."
    )

    latitude: Optional[float] = Field(
        default=None,
        ge=-90.0,
        le=90.0,
        description="Catchment latitude for PET calculation (required for Oudin/Hamon)."
    )

    # =========================================================================
    # Default Parameter Values (11 params)
    # =========================================================================
    default_m: float = Field(default=0.05, description="Transmissivity decay (m)")
    default_lnTe: float = Field(default=1.0, description="Effective log transmissivity ln(m^2/h)")
    default_Srmax: float = Field(default=0.05, description="Max root zone storage (m)")
    default_Sr0: float = Field(default=0.01, description="Initial root zone deficit (m)")
    default_td: float = Field(default=5.0, description="Unsaturated zone delay (h/m)")
    default_k_route: float = Field(default=48.0, description="Routing reservoir coefficient (h)")
    default_DDF: float = Field(default=3.5, description="Degree-day melt factor (mm/degC/day)")
    default_T_melt: float = Field(default=0.0, description="Melt threshold (degC)")
    default_T_snow: float = Field(default=1.0, description="Snow/rain threshold (degC)")
    default_ti_std: float = Field(default=4.0, description="TI distribution spread (-)")
    default_S0: float = Field(default=0.5, description="Initial mean deficit (m)")

    def get_default_params(self) -> Dict[str, float]:
        """Get dictionary of default parameter values."""
        return {
            'm': self.default_m,
            'lnTe': self.default_lnTe,
            'Srmax': self.default_Srmax,
            'Sr0': self.default_Sr0,
            'td': self.default_td,
            'k_route': self.default_k_route,
            'DDF': self.default_DDF,
            'T_melt': self.default_T_melt,
            'T_snow': self.default_T_snow,
            'ti_std': self.default_ti_std,
            'S0': self.default_S0,
        }

    def get_calibration_params(self) -> List[str]:
        """Get list of parameters to calibrate."""
        if not self.params_to_calibrate or self.params_to_calibrate == 'default':
            from .parameters import PARAM_BOUNDS
            return list(PARAM_BOUNDS.keys())
        return [p.strip() for p in self.params_to_calibrate.split(',')]

    model_config = {'extra': 'forbid'}


class TopmodelConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for TOPMODEL.

    Maps between config dictionary keys and TOPMODELConfig schema.
    """

    MODEL_NAME = "TOPMODEL"
    CONFIG_PREFIX = "TOPMODEL_"

    @classmethod
    def get_config_schema(cls) -> type:
        """Return the Pydantic config schema class."""
        return TOPMODELConfig

    @classmethod
    def get_defaults(cls) -> Dict[str, Any]:
        """Get default values for TOPMODEL configuration."""
        return {
            'TOPMODEL_BACKEND': 'jax',
            'TOPMODEL_WARMUP_DAYS': 365,
            'TOPMODEL_PARAMS_TO_CALIBRATE': 'default',
            'TOPMODEL_CALIBRATION_METRIC': 'KGE',
            'TOPMODEL_PET_METHOD': 'input',
            # Default parameters
            'TOPMODEL_DEFAULT_M': 0.05,
            'TOPMODEL_DEFAULT_LNTE': 1.0,
            'TOPMODEL_DEFAULT_SRMAX': 0.05,
            'TOPMODEL_DEFAULT_SR0': 0.01,
            'TOPMODEL_DEFAULT_TD': 5.0,
            'TOPMODEL_DEFAULT_K_ROUTE': 48.0,
            'TOPMODEL_DEFAULT_DDF': 3.5,
            'TOPMODEL_DEFAULT_T_MELT': 0.0,
            'TOPMODEL_DEFAULT_T_SNOW': 1.0,
            'TOPMODEL_DEFAULT_TI_STD': 4.0,
            'TOPMODEL_DEFAULT_S0': 0.5,
        }

    @classmethod
    def _get_legacy_transformers(cls) -> Dict[str, tuple]:
        """Get field transformation functions."""
        return {
            'TOPMODEL_BACKEND': ('backend', str),
            'TOPMODEL_WARMUP_DAYS': ('warmup_days', int),
            'TOPMODEL_PARAMS_TO_CALIBRATE': ('params_to_calibrate', str),
            'TOPMODEL_CALIBRATION_METRIC': ('calibration_metric', str),
            'TOPMODEL_PET_METHOD': ('pet_method', str),
            'TOPMODEL_LATITUDE': ('latitude', float),
            # Default parameters
            'TOPMODEL_DEFAULT_M': ('default_m', float),
            'TOPMODEL_DEFAULT_LNTE': ('default_lnTe', float),
            'TOPMODEL_DEFAULT_SRMAX': ('default_Srmax', float),
            'TOPMODEL_DEFAULT_SR0': ('default_Sr0', float),
            'TOPMODEL_DEFAULT_TD': ('default_td', float),
            'TOPMODEL_DEFAULT_K_ROUTE': ('default_k_route', float),
            'TOPMODEL_DEFAULT_DDF': ('default_DDF', float),
            'TOPMODEL_DEFAULT_T_MELT': ('default_T_melt', float),
            'TOPMODEL_DEFAULT_T_SNOW': ('default_T_snow', float),
            'TOPMODEL_DEFAULT_TI_STD': ('default_ti_std', float),
            'TOPMODEL_DEFAULT_S0': ('default_S0', float),
        }

    @classmethod
    def from_dict(cls, config_dict: Dict[str, Any]) -> TOPMODELConfig:
        """Create TOPMODELConfig from a configuration dictionary."""
        transformers = cls._get_legacy_transformers()
        defaults = cls.get_defaults()

        kwargs = {}
        for config_key, (field_name, field_type) in transformers.items():
            value = config_dict.get(config_key, defaults.get(config_key))
            if value is not None:
                try:
                    kwargs[field_name] = field_type(value)
                except (ValueError, TypeError):
                    kwargs[field_name] = value

        return TOPMODELConfig(**kwargs)

    @classmethod
    def to_dict(cls, config: TOPMODELConfig) -> Dict[str, Any]:
        """Convert TOPMODELConfig to configuration dictionary."""
        transformers = cls._get_legacy_transformers()
        result = {}

        for config_key, (field_name, _) in transformers.items():
            if hasattr(config, field_name):
                result[config_key] = getattr(config, field_name)

        return result
